use std::fs::File;
use std::io::Read;

use crate::exec::sanitize;

const RESOLV_CONF: &str = "/etc/resolv.conf";
const MAX_RESOLV_CONF: u64 = 64 * 1024;

/// Серверы, до которых встроенный DNS Docker (`127.0.0.11`, сети пользователя)
/// доходит из сетевого пространства хоста, если они перечислены в `resolv_conf`.
///
/// Такие запросы не проходят через правила контейнера, поэтому не попадают в xray:
/// приложения получают настоящие адреса вместо fake-IP, а их DNS утекает мимо
/// туннеля. Серверы, заданные явно (`dns:` в compose, `--dns`), Docker опрашивает из
/// пространства контейнера, там их перехватывают правила. Docker отмечает случай
/// комментарием: `# ExtServers: [host(192.168.0.1)]` и `# ExtServers: [1.1.1.1]`.
pub fn docker_dns_via_host(resolv_conf: &str) -> Option<String> {
    let servers = resolv_conf
        .lines()
        .find_map(|line| line.strip_prefix("# ExtServers:"))?
        .trim();
    servers.contains("host(").then(|| sanitize(servers))
}

/// Предупреждение об утечке DNS для содержимого `resolv_conf`, если она есть.
pub fn dns_leak_message(resolv_conf: &str) -> Option<String> {
    docker_dns_via_host(resolv_conf).map(|servers| {
        format!(
            "Docker разрешает имена для этого контейнера через резолвер хоста {servers} \
             в обход перехвата: приложения получают настоящие адреса, а их DNS-запросы \
             утекают мимо туннеля. Задайте контейнеру явный DNS-сервер (compose: \
             `dns: [1.1.1.1]`, docker run: `--dns 1.1.1.1`)"
        )
    })
}

/// Проверяет `/etc/resolv.conf` этого контейнера; `None` — утечки нет или файла нет.
pub fn dns_leak() -> Option<String> {
    let mut text = String::new();
    File::open(RESOLV_CONF)
        .ok()?
        .take(MAX_RESOLV_CONF)
        .read_to_string(&mut text)
        .ok()?;
    dns_leak_message(&text)
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER: &str = "# Generated by Docker Engine.\n\nnameserver 127.0.0.11\n\
                          options ndots:0\n\n# Based on host file: '/etc/resolv.conf' \
                          (internal resolver)\n";

    #[test]
    fn host_namespace_upstreams_are_detected() {
        let via_host = format!("{HEADER}# ExtServers: [host(192.168.0.1)]\n# Overrides: []\n");
        assert_eq!(
            docker_dns_via_host(&via_host).as_deref(),
            Some("[host(192.168.0.1)]")
        );
        let loopback = format!("{HEADER}# ExtServers: [host(127.0.0.53)]\n");
        assert!(docker_dns_via_host(&loopback).is_some());
    }

    #[test]
    fn explicit_upstreams_and_plain_files_are_fine() {
        let explicit =
            format!("{HEADER}# ExtServers: [1.1.1.1 8.8.8.8]\n# Overrides: [nameservers]\n");
        assert_eq!(docker_dns_via_host(&explicit), None);
        let legacy =
            "nameserver 192.168.0.1\n\n# Based on host file: '/etc/resolv.conf' (legacy)\n";
        assert_eq!(docker_dns_via_host(legacy), None);
        assert_eq!(docker_dns_via_host("nameserver 1.1.1.1\n"), None);
        assert_eq!(docker_dns_via_host(""), None);
    }

    #[test]
    fn message_names_the_servers_and_the_fix() {
        let text = format!("{HEADER}# ExtServers: [host(192.168.0.1)]\n");
        let message = dns_leak_message(&text).unwrap();
        assert!(message.contains("[host(192.168.0.1)]"));
        assert!(message.contains("dns: [1.1.1.1]"));
        assert!(dns_leak_message("nameserver 1.1.1.1\n").is_none());
    }

    #[test]
    fn hostile_resolv_conf_cannot_inject_control_characters() {
        let text = "# ExtServers: [host(1.1.1.1)\u{1b}[2J\rspoof]\n";
        let servers = docker_dns_via_host(text).unwrap();
        assert!(!servers.chars().any(char::is_control));
    }
}
