[package]
name = "raycat-subscription"
description = "Разбор ответов панелей подписок: заголовки провайдера, узлы, заглушки"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
raycat-xray = { path = "../xray", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
