[package]
name = "raycat"
description = "Серверный клиент VPN-подписок: шлюз и прокси для хоста и Docker-контейнеров"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
libc.workspace = true
raycat-config.workspace = true
raycat-emulation.workspace = true
raycat-http.workspace = true
raycat-netfilter.workspace = true
raycat-proto.workspace = true
raycat-select.workspace = true
raycat-subscription.workspace = true
raycat-xray.workspace = true
raycat-xray-api.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

[lints]
workspace = true
