GET /sub/capture-android HTTP/1.1
Connection: close
User-agent: Happ/4.7.1/Android/17912103176801703550
X-Device-Locale: en
X-HWID: 1312da0f330f9d0b
X-Device-OS: Android
X-Ver-OS: 14
X-Device-model: sdk_gphone64_x86_64
Host: 10.0.2.2:18080
Accept-Encoding: gzip

