GET /sub/capture-windows HTTP/1.1
Host: 127.0.0.1:18080
User-Agent: Happ/4.3.0/Windows/2609151455503
X-App-Version: 4.3.0
X-Device-Locale: EN
X-Device-Os: Windows
X-Device-Model: runnervmfi6oq_x86_64
X-Hwid: 140da80d-b9fb-4025-bdaf-a293fec29e2b
X-Ver-Os: 11_10.0.26100
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*

